import React, { useState } from 'react';
import { User, PetState, Mood, UserRole } from '../types';

interface SetupModalProps {
  onComplete: (user1: User, user2: User, pet: PetState) => void;
}

const AVATARS = ['🦊', '🐰', '🐼', '🐨', '🐸', '🐷', '🦄', '🐙', '🐵', '🐱', '🐶', '🐣'];

export const SetupModal: React.FC<SetupModalProps> = ({ onComplete }) => {
  const [step, setStep] = useState(1);
  const [u1Name, setU1Name] = useState('');
  const [u2Name, setU2Name] = useState('');
  const [u1Avatar, setU1Avatar] = useState('🦊');
  const [u2Avatar, setU2Avatar] = useState('🐰');
  
  const [petName, setPetName] = useState('');
  const [isSaved, setIsSaved] = useState(false);
  
  // Hardcoded type as requested
  const petType = 'Foca Bebê';

  const handleFinish = () => {
    if (!u1Name || !u2Name || !petName) return;

    // Visual feedback trigger
    setIsSaved(true);

    const user1: User = { name: u1Name, role: UserRole.USER_A, avatar: u1Avatar };
    const user2: User = { name: u2Name, role: UserRole.USER_B, avatar: u2Avatar };
    
    const initialPet: PetState = {
      name: petName,
      type: petType,
      satisfaction: 100,
      hunger: 80,
      happiness: 80,
      energy: 100,
      cleanliness: 100,
      mood: Mood.HAPPY,
      age: 0,
      image: null, // Will be generated by App.tsx based on the specific "Seal" prompt
      isSleeping: false
    };

    // Delay callback to show the animation
    setTimeout(() => {
        onComplete(user1, user2, initialPet);
    }, 1000);
  };

  const inputClass = "w-full p-4 bg-cute-bg border-2 border-transparent rounded-2xl text-cute-text placeholder-cute-text/40 focus:outline-none focus:border-cute-pink/50 focus:bg-white transition-all font-semibold lowercase";

  const AvatarSelector = ({ selected, onSelect }: { selected: string, onSelect: (a: string) => void }) => (
    <div className="flex gap-2 overflow-x-auto py-2 scrollbar-hide">
      {AVATARS.map(avatar => (
        <button
          key={avatar}
          onClick={() => onSelect(avatar)}
          className={`flex-shrink-0 w-10 h-10 rounded-full flex items-center justify-center text-xl transition-all ${
            selected === avatar 
              ? 'bg-primary text-white scale-110 shadow-md ring-2 ring-offset-2 ring-primary' 
              : 'bg-white text-cute-text hover:bg-gray-50 border border-gray-100'
          }`}
        >
          {avatar}
        </button>
      ))}
    </div>
  );

  return (
    <div className="fixed inset-0 bg-[#FFF5F7] z-50 flex items-center justify-center p-6">
      <div className="w-full max-w-sm flex flex-col items-center">
        
        {/* Decorative Header */}
        <div className="w-20 h-20 bg-white rounded-[2rem] shadow-soft mb-8 flex items-center justify-center text-4xl animate-bounce-slow">
            ❤️
        </div>

        <div className="bg-white rounded-[2.5rem] shadow-[0_20px_60px_-15px_rgba(255,183,178,0.3)] p-8 w-full relative overflow-hidden">
          {/* Progress Dot */}
          <div className="absolute top-0 left-0 w-full h-2 bg-gray-100">
             <div className={`h-full bg-primary transition-all duration-500 ${step === 1 ? 'w-1/2' : 'w-full'}`}></div>
          </div>

          <h2 className="text-2xl font-black text-cute-text mb-2 text-center mt-2 lowercase">
            {step === 1 ? "quem são vocês?" : "o bebê"}
          </h2>
          <p className="text-sm text-cute-text/60 text-center mb-6 font-medium lowercase">
            {step === 1 ? "vamos criar um lar aconchegante." : "dê um nome para o mascote."}
          </p>

          {step === 1 && (
            <div className="space-y-5 animate-fade-in">
              {/* User 1 */}
              <div>
                <label className="block text-xs font-bold text-cute-text/50 uppercase tracking-wider ml-4 mb-1 lowercase">você</label>
                <input 
                  type="text" 
                  value={u1Name} 
                  onChange={e => setU1Name(e.target.value)}
                  className={inputClass}
                  placeholder="seu apelido fofo"
                />
                <div className="mt-2 px-1">
                   <AvatarSelector selected={u1Avatar} onSelect={setU1Avatar} />
                </div>
              </div>

              {/* User 2 */}
              <div>
                <label className="block text-xs font-bold text-cute-text/50 uppercase tracking-wider ml-4 mb-1 lowercase">seu amor</label>
                <input 
                  type="text" 
                  value={u2Name} 
                  onChange={e => setU2Name(e.target.value)}
                  className={inputClass}
                  placeholder="apelido dele(a)"
                />
                <div className="mt-2 px-1">
                   <AvatarSelector selected={u2Avatar} onSelect={setU2Avatar} />
                </div>
              </div>

              <button 
                onClick={() => u1Name && u2Name && setStep(2)}
                className="w-full bg-primary text-white font-bold py-4 rounded-2xl mt-4 shadow-lg shadow-primary/30 hover:shadow-xl hover:scale-[1.02] active:scale-95 transition-all lowercase"
              >
                continuar ✨
              </button>
            </div>
          )}

          {step === 2 && (
            <div className="space-y-4 animate-fade-in">
              {/* Mascot Preview Card */}
              <div className="w-full bg-[#E0F7FA] rounded-2xl p-4 flex flex-col items-center justify-center border-2 border-[#B2EBF2] mb-4">
                  <span className="text-4xl mb-2">🦭</span>
                  <span className="text-xs font-bold text-teal-700 uppercase tracking-widest lowercase">mascote oficial</span>
                  <span className="text-sm font-black text-teal-900 lowercase">foca bebê</span>
              </div>

              <div>
                <label className="block text-xs font-bold text-cute-text/50 uppercase tracking-wider ml-4 mb-1 lowercase">nome do bebê</label>
                <input 
                  type="text" 
                  value={petName} 
                  onChange={e => setPetName(e.target.value)}
                  className={inputClass}
                  placeholder="ex: fofucho"
                />
              </div>

              <button 
                onClick={handleFinish}
                disabled={!petName || isSaved}
                className={`w-full font-bold py-4 rounded-2xl mt-4 shadow-lg transition-all duration-300 transform lowercase
                    ${isSaved 
                        ? 'bg-green-500 text-white scale-105 shadow-green-500/30' 
                        : 'bg-cute-green text-teal-800 shadow-cute-green/30 hover:shadow-xl hover:scale-[1.02] active:scale-95'
                    } disabled:opacity-50 disabled:shadow-none`}
              >
                {isSaved ? (
                    <span className="flex items-center justify-center gap-2 lowercase">
                        nome salvo! 🎉
                    </span>
                ) : "nascer! 🐣"}
              </button>
              
              {!isSaved && (
                  <button onClick={() => setStep(1)} className="w-full text-center text-xs text-cute-text/40 font-bold hover:text-cute-text transition py-2 lowercase">
                     voltar
                  </button>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
};